package com.aureliajets.ui

data class Airport(
    val code: String,
    val name: String,
    val city: String,
    val country: String
) {
    val display: String get() = "$city ($code)"
    val full: String get() = "$city, $country — $name"
}

val popularAirports = listOf(
    Airport("DXB", "Dubai International Airport", "Dubai", "UAE"),
    Airport("LHR", "Heathrow Airport", "London", "UK"),
    Airport("JFK", "John F. Kennedy International Airport", "New York", "USA"),
    Airport("LAX", "Los Angeles International Airport", "Los Angeles", "USA"),
    Airport("CDG", "Charles de Gaulle Airport", "Paris", "France"),
    Airport("SIN", "Changi Airport", "Singapore", "Singapore"),
    Airport("HND", "Haneda Airport", "Tokyo", "Japan"),
    Airport("FRA", "Frankfurt Airport", "Frankfurt", "Germany"),
    Airport("AMS", "Amsterdam Airport Schiphol", "Amsterdam", "Netherlands"),
    Airport("IST", "Istanbul Airport", "Istanbul", "Turkey"),
    Airport("ORD", "O'Hare International Airport", "Chicago", "USA"),
    Airport("MIA", "Miami International Airport", "Miami", "USA"),
    Airport("SFO", "San Francisco International Airport", "San Francisco", "USA"),
    Airport("BKK", "Suvarnabhumi Airport", "Bangkok", "Thailand"),
    Airport("KUL", "Kuala Lumpur International Airport", "Kuala Lumpur", "Malaysia"),
    Airport("GVA", "Geneva Airport", "Geneva", "Switzerland"),
    Airport("ZRH", "Zurich Airport", "Zurich", "Switzerland"),
    Airport("MXP", "Milan Malpensa Airport", "Milan", "Italy"),
    Airport("FCO", "Leonardo da Vinci Airport", "Rome", "Italy"),
    Airport("BCN", "El Prat Airport", "Barcelona", "Spain"),
    Airport("MAD", "Adolfo Suárez Madrid–Barajas Airport", "Madrid", "Spain"),
    Airport("LIS", "Humberto Delgado Airport", "Lisbon", "Portugal"),
    Airport("ATH", "Athens International Airport", "Athens", "Greece"),
    Airport("CPH", "Copenhagen Airport", "Copenhagen", "Denmark"),
    Airport("ARN", "Stockholm Arlanda Airport", "Stockholm", "Sweden"),
    Airport("OSL", "Oslo Airport", "Oslo", "Norway"),
    Airport("HEL", "Helsinki Airport", "Helsinki", "Finland"),
    Airport("VIE", "Vienna International Airport", "Vienna", "Austria"),
    Airport("PRG", "Václav Havel Airport Prague", "Prague", "Czech Republic"),
    Airport("WAW", "Warsaw Chopin Airport", "Warsaw", "Poland"),
    Airport("BUD", "Budapest Ferenc Liszt Airport", "Budapest", "Hungary"),
    Airport("SYD", "Sydney Kingsford Smith Airport", "Sydney", "Australia"),
    Airport("MEL", "Melbourne Airport", "Melbourne", "Australia"),
    Airport("AKL", "Auckland Airport", "Auckland", "New Zealand"),
    Airport("NRT", "Narita International Airport", "Tokyo", "Japan"),
    Airport("ICN", "Incheon International Airport", "Seoul", "South Korea"),
    Airport("PEK", "Beijing Capital International Airport", "Beijing", "China"),
    Airport("PVG", "Shanghai Pudong International Airport", "Shanghai", "China"),
    Airport("HKG", "Hong Kong International Airport", "Hong Kong", "China"),
    Airport("TPE", "Taiwan Taoyuan International Airport", "Taipei", "Taiwan"),
    Airport("BOM", "Chhatrapati Shivaji Maharaj International Airport", "Mumbai", "India"),
    Airport("DEL", "Indira Gandhi International Airport", "Delhi", "India"),
    Airport("BLR", "Kempegowda International Airport", "Bengaluru", "India"),
    Airport("LHE", "Allama Iqbal International Airport", "Lahore", "Pakistan"),
    Airport("KHI", "Jinnah International Airport", "Karachi", "Pakistan"),
    Airport("ISB", "Islamabad International Airport", "Islamabad", "Pakistan"),
    Airport("DAC", "Hazrat Shahjalal International Airport", "Dhaka", "Bangladesh"),
    Airport("CMB", "Bandaranaike International Airport", "Colombo", "Sri Lanka"),
    Airport("KTM", "Tribhuvan International Airport", "Kathmandu", "Nepal"),
    Airport("CAI", "Cairo International Airport", "Cairo", "Egypt"),
    Airport("JNB", "O.R. Tambo International Airport", "Johannesburg", "South Africa"),
    Airport("NBO", "Jomo Kenyatta International Airport", "Nairobi", "Kenya"),
    Airport("LOS", "Murtala Muhammed International Airport", "Lagos", "Nigeria"),
    Airport("CMN", "Mohammed V International Airport", "Casablanca", "Morocco"),
    Airport("TUN", "Tunis-Carthage International Airport", "Tunis", "Tunisia"),
    Airport("ADD", "Addis Ababa Bole International Airport", "Addis Ababa", "Ethiopia"),
    Airport("GRU", "São Paulo Guarulhos International Airport", "São Paulo", "Brazil"),
    Airport("GIG", "Rio de Janeiro Galeão Airport", "Rio de Janeiro", "Brazil"),
    Airport("BOG", "El Dorado International Airport", "Bogotá", "Colombia"),
    Airport("LIM", "Jorge Chávez International Airport", "Lima", "Peru"),
    Airport("SCL", "Arturo Merino Benítez Airport", "Santiago", "Chile"),
    Airport("EZE", "Ministro Pistarini International Airport", "Buenos Aires", "Argentina"),
    Airport("MEX", "Mexico City International Airport", "Mexico City", "Mexico"),
    Airport("YYZ", "Toronto Pearson International Airport", "Toronto", "Canada"),
    Airport("YVR", "Vancouver International Airport", "Vancouver", "Canada"),
    Airport("MCO", "Orlando International Airport", "Orlando", "USA"),
    Airport("LAS", "Harry Reid International Airport", "Las Vegas", "USA"),
    Airport("DFW", "Dallas/Fort Worth International Airport", "Dallas", "USA"),
    Airport("SEA", "Seattle–Tacoma International Airport", "Seattle", "USA"),
    Airport("BOS", "Logan International Airport", "Boston", "USA"),
    Airport("IAD", "Washington Dulles International Airport", "Washington D.C.", "USA"),
    Airport("ATL", "Hartsfield-Jackson Atlanta International Airport", "Atlanta", "USA"),
    Airport("MUC", "Munich Airport", "Munich", "Germany"),
    Airport("TXL", "Berlin Brandenburg Airport", "Berlin", "Germany"),
    Airport("MAN", "Manchester Airport", "Manchester", "UK"),
    Airport("EDI", "Edinburgh Airport", "Edinburgh", "UK"),
    Airport("NCE", "Nice Côte d'Azur Airport", "Nice", "France"),
    Airport("LYS", "Lyon–Saint Exupéry Airport", "Lyon", "France"),
    Airport("ORY", "Paris Orly Airport", "Paris", "France"),
    Airport("AUH", "Abu Dhabi International Airport", "Abu Dhabi", "UAE"),
    Airport("DOH", "Hamad International Airport", "Doha", "Qatar"),
    Airport("KWI", "Kuwait International Airport", "Kuwait City", "Kuwait"),
    Airport("BAH", "Bahrain International Airport", "Manama", "Bahrain"),
    Airport("MCT", "Muscat International Airport", "Muscat", "Oman"),
    Airport("AMM", "Queen Alia International Airport", "Amman", "Jordan"),
    Airport("BEY", "Rafic Hariri International Airport", "Beirut", "Lebanon"),
    Airport("TLV", "Ben Gurion Airport", "Tel Aviv", "Israel"),
    Airport("RUH", "King Khalid International Airport", "Riyadh", "Saudi Arabia"),
    Airport("JED", "King Abdulaziz International Airport", "Jeddah", "Saudi Arabia"),
    Airport("CGK", "Soekarno-Hatta International Airport", "Jakarta", "Indonesia"),
    Airport("MNL", "Ninoy Aquino International Airport", "Manila", "Philippines"),
    Airport("SGN", "Tan Son Nhat International Airport", "Ho Chi Minh City", "Vietnam"),
    Airport("HAN", "Noi Bai International Airport", "Hanoi", "Vietnam"),
    Airport("RGN", "Yangon International Airport", "Yangon", "Myanmar"),
    Airport("PNH", "Phnom Penh International Airport", "Phnom Penh", "Cambodia"),
    Airport("VTE", "Wattay International Airport", "Vientiane", "Laos"),
    Airport("MLE", "Velana International Airport", "Malé", "Maldives"),
    Airport("NAN", "Nadi International Airport", "Nadi", "Fiji"),
    Airport("PPT", "Faa'a International Airport", "Papeete", "French Polynesia")
)

fun searchAirports(query: String): List<Airport> {
    if (query.length < 2) return emptyList()
    val q = query.lowercase()
    return popularAirports.filter {
        it.city.lowercase().contains(q) ||
        it.code.lowercase().contains(q) ||
        it.country.lowercase().contains(q) ||
        it.name.lowercase().contains(q)
    }.take(6)
}
